[Draft] support upsert sql
SeaQL/sea-query pull request #167
Opened 2021-10-18 03:31 UTC by baoyachi

Inprogres work for https://github.com/SeaQL/sea-orm/issues/187

2021-11-25 11:45 UTC, billy1624 commented
Hey @baoyachi, sorry for the delay.

I'm on the way home now and I wonder if MySQL & SQLite supports similar upcert syntax?

2021-11-26 01:30 UTC, Progdrasil commented
[SQLite supports it](https://www.sqlite.org/lang_UPSERT.html) but MySQL is ... [Complicated](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)

2021-11-26 04:41 UTC, billy1624 requested changes

2021-11-26 04:41 UTC, billy1624 commented on src/query/upsert.rs
> +    }
For all these test cases could we assert it against a String?

2021-11-26 04:54 UTC, billy1624 commented
> [SQLite supports it](https://www.sqlite.org/lang_UPSERT.html) but MySQL is ... [Complicated](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)

I see... basically MySQL don't have `DO NOTHING` and any extra conditioning. It just have `ON DUPLICATE KEY UPDATE`
```sql
INSERT [LOW_PRIORITY | DELAYED | HIGH_PRIORITY] [IGNORE]
  [INTO] tbl_name [PARTITION (partition_list)] [(col,...)]
  {VALUES | VALUE} ({expr | DEFAULT},...),(...),...
  [ ON DUPLICATE KEY UPDATE
    col=expr
      [, col=expr] ... ]
```

REF:
- https://mariadb.com/kb/en/insert-on-duplicate-key-update/
- https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

2021-11-26 04:55 UTC, billy1624 commented on src/backend/query_builder.rs
> +    ) {
We should implement a separate version of `prepare_upsert` for MySQL

2021-12-30 00:50 UTC, jamiepine commented
Noticed the author of this wonderful PR hasn't returned to make the requested changes. I would love to help get this one moving as I need it in my project. 

Though, I am wondering if this will work for `insert_many` operations?

2021-12-30 02:57 UTC, billy1624 commented
> Though, I am wondering if this will work for `insert_many` operations?

I assumed you are talk PostgreSQL specifically. I found the following snippet online.

```sql
INSERT INTO med.coinprices (symbol, currency, price_usd, volume_24h) VALUES
	('BTC', 'Bitcoin', 60000, 40000000000)
	, ('XDG', 'Dogecoin', 0.2181, 1983534547)
ON CONFLICT (symbol, currency)
DO UPDATE SET
	price_usd = EXCLUDED.price_usd
	, volume_24h = EXCLUDED.volume_24h;
```

https://towardsdatascience.com/postgresql-how-to-upsert-safely-easily-and-fast-246040514933

2021-12-30 03:00 UTC, billy1624 commented
Just found MySQL & SQLite have similar features.

- SQLite also have a `excluded` keyword: https://www.sqlite.org/lang_UPSERT.html
- While, MySQL have a keyword named `new`: https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

2021-12-30 10:41 UTC, jamiepine commented
Oh I should have mentioned, in my case I'm using SQLite. I only just discovered that it supports `ON CONFLICT IGNORE` in the schema itself, so that was able to solve my issue with `insert_many`.
```sql
CREATE TABLE files (
-- ...
   meta_checksum TEXT NOT NULL UNIQUE ON CONFLICT IGNORE,
-- ...
);
```

```rust
let files: Vec<file::ActiveModel>;

file::Entity::insert_many(files).exec(db).await?;
```
So if anything this is a good workaround for SQLite users.

2022-03-24 10:36 UTC, billy1624 commented
Hey @baoyachi, I'll convert this to draft due to inactive :)

2022-03-24 10:37 UTC, billy1624 commented
I'm implementing a simple version of `ON CONFLICT` on #279

2022-03-25 02:23 UTC, closed without merging