Feature/issues 229 add column if not exists
SeaQL/sea-query pull request #278
Opened 2022-03-22 19:14 UTC by ikrivosheev

## PR Info

- Closes <https://github.com/SeaQL/sea-query/issues/229>

- Dependencies:
  - https://github.com/SeaQL/sea-query/pull/277

## Adds

Add support for query like: 
```
ALTER TABLE name
    ADD COLUMN IF NOT EXISTS column_name data_type
```

for PostgreSQL and for MySQL. For SQLLite this is ignored

2022-03-24 15:21 UTC, tyt2y3 commented
I don't think this works for MySQL, may be just MariaDB?

2022-03-24 15:21 UTC, tyt2y3 requested changes
I like the addition of this API. But a `bool` does not seem forword looking, we might want to create a new type `AddColumnOption` (or some reasonable name)?

2022-03-30 08:32 UTC, ikrivosheev commented
@tyt2y3 I have done. Can you review it please?)

2022-04-03 07:30 UTC, tyt2y3 approved these changes

2022-04-03 07:30 UTC, merged