query(union): add intersect and except types
SeaQL/sea-query pull request #438
Opened 2022-09-13 16:36 UTC by Martichou

## PR Info

- Closes https://github.com/SeaQL/sea-query/issues/427

## Changes

- [x] add the INTERSECT and EXCEPT operators

2022-09-13 17:48 UTC, ikrivosheev requested changes
@Martichou thank you for your contribution! Can you run `rustfmt`?

2022-09-13 17:51 UTC, Martichou commented
Done! I forgot the most basic thing to do, my bad :)

2022-09-13 17:59 UTC, ikrivosheev approved these changes

2022-09-17 09:32 UTC, tyt2y3 approved these changes

2022-09-17 09:36 UTC, merged