Add support for NULLS NOT DISTINCT clause
SeaQL/sea-query pull request #532
Opened 2022-11-27 04:07 UTC by rstular

PostgreSQL 15 [added support](https://www.postgresql.org/docs/15/release-15.html#id-1.11.6.6.5) (section `E.2.3.1.2. Indexes`) for the `NULLS NOT DISTINCT` clause in index creation, which, as the name suggests, causes nulls to not be treated as distinct values when evaluating the `UNIQUE` constraint.

However, using this feature on an unsupported Postgres version will cause an SQL error - I'm not sure how/if this is handled in this project.

Also closes #509

2022-11-28 09:41 UTC, ikrivosheev commented on src/index/create.rs
> +    pub fn is_nulls_not_distinct(&self) -> bool {
I don't thin we should invent new name, for me is ok.

2022-11-28 09:41 UTC, ikrivosheev approved these changes

2022-11-29 07:35 UTC, billy1624 requested changes
Hey @rstular, thanks for contributing!!

I think we miss a edge case (this should be added as test case):

```rs
assert_eq!(
    Table::create()
        .table(Glyph::Table)
        .col(ColumnDef::new(Glyph::Image).json())
        .col(ColumnDef::new(Glyph::Aspect).json_binary())
        .index(
            Index::create()
                .unique()
                .nulls_not_distinct()
                .name("idx-glyph-aspect-image")
                .table(Glyph::Table)
                .col(Glyph::Aspect)
                .col(Glyph::Image)
        )
        .to_string(PostgresQueryBuilder),
    [
        r#"CREATE TABLE "glyph" ("#,
        r#""image" json,"#,
        r#""aspect" jsonb,"#,
        r#"CONSTRAINT "idx-glyph-aspect-image" UNIQUE NULLS NOT DISTINCT ("aspect", "image")"#,
        r#")"#,
    ]
    .join(" ")
);
```

Hence, we need to modify this part as well:

https://github.com/SeaQL/sea-query/blob/c6becfa62120e4dc808c71320b6547619865c27d/src/backend/postgres/index.rs#L73-L80

2022-12-02 02:57 UTC, billy1624 approved these changes
Awesome!! Thanks! @rstular

2022-12-02 09:16 UTC, merged

2022-12-02 09:20 UTC, billy1624 commented
See you around on GitHub @rstular :)
Thanks again!